[package]
name = "bugrepro"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
after-effects = { version = "0.2.1" }

[build-dependencies]
pipl = { git = "https://github.com/virtualritz/after-effects.git" }
